const FETCH_ALL = 'FETCH_ALL';
const FETCH_POST = 'FETCH_POST';
const FETCH_BY_CREATOR = 'FETCH_BY_CREATOR';
const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const LIKE = 'LIKE';
const DELETE = 'DELETE';
const SEARCH = 'SEARCH';
const COMMENT = 'COMMENT';

const LOGOUT = 'LOGOUT';
const AUTH = 'AUTH';

const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING';

export {
  FETCH_ALL,
  FETCH_POST,
  FETCH_BY_CREATOR,
  CREATE,
  UPDATE,
  LIKE,
  DELETE,
  SEARCH,
  COMMENT,
  LOGOUT,
  AUTH,
  START_LOADING,
  END_LOADING
};
